//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CommTestSample.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_COMMTESTSAMPLE_DIALOG       102
#define IDR_MAINFRAME                   128
#define IDC_IPADDR                      1000
#define IDC_BUTTON_Connect              1001
#define IDC_BUTTON_Disconnect           1002
#define IDC_EDIT_Log                    1003
#define IDC_RADIO_Query_Brt             1004
#define IDC_RADIO_Query_Cst             1005
#define IDC_RADIO_Query_Mag             1006
#define IDC_RADIO_Query_RotAngle        1007
#define IDC_RADIO_Query_WD              1008
#define IDC_RADIO_Query_Stigmator       1009
#define IDC_RADIO_Query_HV              1010
#define IDC_RADIO_Query_Fila            1011
#define IDC_RADIO_Query_BeamCurrent     1012
#define IDC_RADIO_Query_RotAngleInit    1013
#define IDC_RADIO_Stage_Status          1014
#define IDC_RADIO_Stage_Grating         1015
#define IDC_RADIO_Stage_Range           1016
#define IDC_RADIO_Stage_Position        1017
#define IDC_RADIO_ScanCtrl_Type1        1019
#define IDC_RADIO_ScanCtrl_Type2        1020
#define IDC_RADIO_ScanCtrl_Type3        1021
#define IDC_RADIO_ScanCtrl_Type4        1022
#define IDC_RADIO_ScanCtrl_Type5        1023
#define IDC_RADIO_ScanCtrl_Speed1       1024
#define IDC_RADIO_ScanCtrl_Speed2       1025
#define IDC_RADIO_ScanCtrl_Speed3       1026
#define IDC_RADIO_ScanCtrl_Speed4       1027
#define IDC_RADIO_ScanCtrl_Reso1        1028
#define IDC_RADIO_ScanCtrl_Reso2        1029
#define IDC_RADIO_ScanCtrl_Reso3        1030
#define IDC_EDIT_Brightness2            1030
#define IDC_BUTTON_Stage_Position_Set   1031
#define IDC_EDIT_Stage_Position_X       1032
#define IDC_EDIT_Stage_Position_Y       1033
#define IDC_EDIT_Version                1034
#define IDC_RADIO_ScanCtrl_Type6        1034
#define IDC_EDIT_WD                     1035
#define IDC_EDIT_Stage_Grating          1036
#define IDC_EDIT_Stage_Range            1037
#define IDC_EDIT_Stage_Status           1038
#define IDC_EDIT_Mag                    1039
#define IDC_EDIT_ScnRotAngle            1040
#define IDC_EDIT_Stig_X                 1041
#define IDC_EDIT_Stig_Y                 1042
#define IDC_BUTTON_SetMag               1043
#define IDC_BUTTON_SetScnRotAngle       1044
#define IDC_BUTTON_SetStig              1045
#define IDC_EDIT_HV                     1046
#define IDC_EDIT_Fila                   1047
#define IDC_BUTTON_SetHV                1048
#define IDC_BUTTON_SetFila              1049
#define IDC_EDIT_BeamCurrent            1050
#define IDC_BUTTON_SetBeamCurrent       1051
#define IDC_EDIT_ScnRotAngleInit        1052
#define IDC_BUTTON_Stage_Stop           1053
#define IDC_BUTTON_AutoBC               1054
#define IDC_STATIC_Rect                 1055
#define IDC_RADIO_ScanCtrl_Type7        1056
#define IDC_RADIO_Query_MagRange        1057
#define IDC_EDIT_Brightness             1058
#define IDC_EDIT_Contrast               1059
#define IDC_BUTTON_SetBrt               1060
#define IDC_BUTTON_SetCst               1061
#define IDC_RADIO_Query_GunStatus       1062
#define IDC_EDIT_GunStatus              1063
#define IDC_RADIO_Query_VacStatus       1064
#define IDC_EDIT_VacStatus              1065
#define IDC_BUTTON_ShutdownBeam         1066
#define IDC_EDIT_MagRange               1067
#define IDC_RADIO_Type_SEM              1068
#define IDC_EDIT_SEMType                1069
#define IDC_RADIO_Type_HV               1070
#define IDC_EDIT_HVType                 1071
#define IDC_EDIT_WD2                    1072
#define IDC_RADIO_Query_EMI             1073
#define IDC_EDIT_EMI                    1074
#define IDC_EDIT_Contrast2              1075
#define IDC_EDIT_Mag2                   1076
#define IDC_EDIT_ScnRotAngle2           1077
#define IDC_EDIT_Stig_X2                1078
#define IDC_EDIT_Stig_Y2                1079
#define IDC_EDIT_HV2                    1080
#define IDC_EDIT_Fila2                  1081
#define IDC_EDIT_BeamCurrent2           1082
#define IDC_BUTTON_SetWD                1083
#define IDC_RADIO_Query_All             1084
#define IDC_CHECK_Polling               1085
#define IDC_BUTTON_Clear                1086
#define IDC_EDIT_Stage_Position_Z       1087
#define IDC_EDIT_Stage_Position_R       1088
#define IDC_EDIT_Stage_Position_T       1089
#define IDC_EDIT_Stage_Position_X2      1090
#define IDC_EDIT_Stage_Position_Y2      1091
#define IDC_EDIT_Stage_Position_Z2      1092
#define IDC_EDIT_Stage_Position_R2      1093
#define IDC_EDIT_Stage_Position_T2      1094
#define IDC_BUTTON_Log_Clear            1095
#define IDC_BUTTON_Stage_GoHome         1096
#define IDC_RADIO_Query_FOV             1097
#define IDC_CHECK_ScanSpots             1098
#define IDC_STATIC_IMAGE                1099
#define IDC_EDIT_FOV                    1100
#define IDC_RADIO_Query_Speed           1101
#define IDC_EDIT_Speed                  1102
#define IDC_RADIO_Query_Resolution      1103
#define IDC_EDIT_Resolution             1105
#define IDC_BUTTON_Image_Clear          1106
#define IDC_RADIO_Query_FrameData       1107
#define IDC_RADIO_Query_Image           1109
#define IDC_BUTTON_Save_Params          1110
#define IDC_BUTTON_Load_Params          1111

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1112
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
