// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "semcorectrlpanel_stand3.h"

// Dispatch interfaces referenced by this interface
#include "font.h"

/////////////////////////////////////////////////////////////////////////////
// CSemCoreCtrlPanel_Stand3

IMPLEMENT_DYNCREATE(CSemCoreCtrlPanel_Stand3, CSemCoreCtrlPanelCommonMap)

/////////////////////////////////////////////////////////////////////////////
// CSemCoreCtrlPanel_Stand3 properties

BOOL CSemCoreCtrlPanel_Stand3::GetCaptionVisible()
{
	BOOL result;
	GetProperty(0x1, VT_BOOL, (void*)&result);
	return result;
}

void CSemCoreCtrlPanel_Stand3::SetCaptionVisible(BOOL propVal)
{
	SetProperty(0x1, VT_BOOL, propVal);
}

OLE_COLOR CSemCoreCtrlPanel_Stand3::GetBackColor()
{
	OLE_COLOR result;
	GetProperty(DISPID_BACKCOLOR, VT_I4, (void*)&result);
	return result;
}

void CSemCoreCtrlPanel_Stand3::SetBackColor(OLE_COLOR propVal)
{
	SetProperty(DISPID_BACKCOLOR, VT_I4, propVal);
}

OLE_COLOR CSemCoreCtrlPanel_Stand3::GetForeColor()
{
	OLE_COLOR result;
	GetProperty(DISPID_FORECOLOR, VT_I4, (void*)&result);
	return result;
}

void CSemCoreCtrlPanel_Stand3::SetForeColor(OLE_COLOR propVal)
{
	SetProperty(DISPID_FORECOLOR, VT_I4, propVal);
}

COleFont CSemCoreCtrlPanel_Stand3::GetFont()
{
	LPDISPATCH pDispatch;
	GetProperty(DISPID_FONT, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CSemCoreCtrlPanel_Stand3::SetFont(LPDISPATCH propVal)
{
	SetProperty(DISPID_FONT, VT_DISPATCH, propVal);
}

CString CSemCoreCtrlPanel_Stand3::GetCaption()
{
	CString result;
	GetProperty(DISPID_CAPTION, VT_BSTR, (void*)&result);
	return result;
}

void CSemCoreCtrlPanel_Stand3::SetCaption(LPCTSTR propVal)
{
	SetProperty(DISPID_CAPTION, VT_BSTR, propVal);
}

BOOL CSemCoreCtrlPanel_Stand3::GetDebugInfoVisible()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CSemCoreCtrlPanel_Stand3::SetDebugInfoVisible(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

BOOL CSemCoreCtrlPanel_Stand3::GetGradeVisible()
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void CSemCoreCtrlPanel_Stand3::SetGradeVisible(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CSemCoreCtrlPanel_Stand3 operations

void CSemCoreCtrlPanel_Stand3::Bind(const VARIANT& ClassID, const VARIANT& SerialNumber)
{
	CSemCoreCtrlPanelCommonMap::Bind( ClassID, SerialNumber );

	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &ClassID, &SerialNumber);
}

void CSemCoreCtrlPanel_Stand3::Enable(const VARIANT& Enabled, const VARIANT& Flag)
{
	CSemCoreCtrlPanelCommonMap::Enable( Enabled, Flag );

	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &Enabled, &Flag);
}

void CSemCoreCtrlPanel_Stand3::SetRange(const VARIANT& Xmin, const VARIANT& Xmax, const VARIANT& Ymin, const VARIANT& Ymax)
{
	CSemCoreCtrlPanelCommonMap::SetRange( Xmin, Xmax, Ymin, Ymax );

	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &Xmin, &Xmax, &Ymin, &Ymax);
}

void CSemCoreCtrlPanel_Stand3::SetPos(const VARIANT& Xpos, const VARIANT& Ypos, const VARIANT& Flag)
{
	CSemCoreCtrlPanelCommonMap::SetPos( Xpos, Ypos, Flag );

	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &Xpos, &Ypos, &Flag);
}

void CSemCoreCtrlPanel_Stand3::SyncPos(const VARIANT& Xpos, const VARIANT& Ypos, const VARIANT& Flag)
{
	CSemCoreCtrlPanelCommonMap::SyncPos( Xpos, Ypos, Flag );

	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &Xpos, &Ypos, &Flag);
}

void CSemCoreCtrlPanel_Stand3::SyncText(LPCTSTR strX, LPCTSTR strY, const VARIANT& Flag)
{
	CSemCoreCtrlPanelCommonMap::SyncText( strX, strY, Flag);

	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_VARIANT;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strX, strY, &Flag);
}

void CSemCoreCtrlPanel_Stand3::SyncResString(const VARIANT& ResourceID, LPCTSTR strRes)
{
	static BYTE parms[] =
		VTS_VARIANT VTS_BSTR;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &ResourceID, strRes);
}

void CSemCoreCtrlPanel_Stand3::SyncString(const VARIANT& ResourceID, const VARIANT& ResourceString)
{
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		&ResourceID, &ResourceString);
}

void CSemCoreCtrlPanel_Stand3::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
