#if !defined(AFX_SEMCORECTRLPANEL_STAND9_H__8DF01BBD_B836_4818_B8EB_5D0A930E8D19__INCLUDED_)
#define AFX_SEMCORECTRLPANEL_STAND9_H__8DF01BBD_B836_4818_B8EB_5D0A930E8D19__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.
#include "SemCoreCtrlPanelCommonMap.h"

// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CSemCoreCtrlPanel_Stand9 wrapper class

class CSemCoreCtrlPanel_Stand9 : public CSemCoreCtrlPanelCommonMap
{
protected:
	DECLARE_DYNCREATE(CSemCoreCtrlPanel_Stand9)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xe6ffa1c0, 0x7787, 0x41d9, { 0x8b, 0xa6, 0xb4, 0xc5, 0x12, 0xaf, 0x9, 0xe3 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	BOOL GetCaptionVisible();
	void SetCaptionVisible(BOOL);
	OLE_COLOR GetBackColor();
	void SetBackColor(OLE_COLOR);
	OLE_COLOR GetForeColor();
	void SetForeColor(OLE_COLOR);
	COleFont GetFont();
	void SetFont(LPDISPATCH);
	CString GetCaption();
	void SetCaption(LPCTSTR);
	BOOL GetDebugInfoVisible();
	void SetDebugInfoVisible(BOOL);
	BOOL GetNewDisplayMode();
	void SetNewDisplayMode(BOOL);

// Operations
public:
	void Bind(const VARIANT& ClassID, const VARIANT& SerialNumber);
	void Enable(const VARIANT& Enabled, const VARIANT& Flag);
	void SetRange(const VARIANT& Xmin, const VARIANT& Xmax, const VARIANT& Ymin, const VARIANT& Ymax);
	void SetPos(const VARIANT& Xpos, const VARIANT& Ypos, const VARIANT& Flag);
	void SyncPos(const VARIANT& Xpos, const VARIANT& Ypos, const VARIANT& Flag);
	void SyncText(LPCTSTR strX, LPCTSTR strY, const VARIANT& Flag);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SEMCORECTRLPANEL_STAND9_H__955019FB_B9B5_49F4_A003_36505FF33312__INCLUDED_)
