#if !defined(AFX_SEMCORECTRLPANEL_STAND6_H__419B76EE_FBEC_4786_8D02_430B6B7896FA__INCLUDED_)
#define AFX_SEMCORECTRLPANEL_STAND6_H__419B76EE_FBEC_4786_8D02_430B6B7896FA__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.
#include "SemCoreCtrlPanelCommonMap.h"


// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CSemCoreCtrlPanel_Stand6 wrapper class

class CSemCoreCtrlPanel_Stand6 : public CSemCoreCtrlPanelCommonMap
{
protected:
	DECLARE_DYNCREATE(CSemCoreCtrlPanel_Stand6)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x957fc761, 0x96db, 0x40d2, { 0x97, 0x52, 0x5a, 0x79, 0x2, 0x22, 0xc4, 0x98 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	BOOL GetCaptionVisible();
	void SetCaptionVisible(BOOL);
	OLE_COLOR GetBackColor();
	void SetBackColor(OLE_COLOR);
	OLE_COLOR GetForeColor();
	void SetForeColor(OLE_COLOR);
	COleFont GetFont();
	void SetFont(LPDISPATCH);
	CString GetCaption();
	void SetCaption(LPCTSTR);
	BOOL GetDebugInfoVisible();
	void SetDebugInfoVisible(BOOL);
	BOOL GetGradeVisible();
	void SetGradeVisible(BOOL);
	CString GetXMinString();
	void SetXMinString(LPCTSTR);
	CString GetXMaxString();
	void SetXMaxString(LPCTSTR);
	unsigned long GetGradeColor();
	void SetGradeColor(unsigned long);
	COleFont GetGradeFont();
	void SetGradeFont(LPDISPATCH);
	short GetGradeState();
	void SetGradeState(short);
	BOOL GetAutoVisible();
	void SetAutoVisible(BOOL);

// Operations
public:
	void Bind(const VARIANT& ClassID, const VARIANT& SerialNumber);
	void Enable(const VARIANT& Enabled, const VARIANT& Flag);
	void SetRange(const VARIANT& Xmin, const VARIANT& Xmax, const VARIANT& Ymin, const VARIANT& Ymax);
	void SetPos(const VARIANT& Xpos, const VARIANT& Ypos, const VARIANT& Flag);
	void SyncPos(const VARIANT& Xpos, const VARIANT& Ypos, const VARIANT& Flag);
	void SyncText(LPCTSTR strX, LPCTSTR strY, const VARIANT& Flag);
	void SyncResString(const VARIANT& ResourceID, LPCTSTR strRes);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SEMCORECTRLPANEL_STAND6_H__419B76EE_FBEC_4786_8D02_430B6B7896FA__INCLUDED_)
