// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "semcorectrlpanel_stand4.h"

/////////////////////////////////////////////////////////////////////////////
// CSemCoreCtrlPanel_Stand4

IMPLEMENT_DYNCREATE(CSemCoreCtrlPanel_Stand4, CSemCoreCtrlPanelCommonMap)

/////////////////////////////////////////////////////////////////////////////
// CSemCoreCtrlPanel_Stand4 properties

CString CSemCoreCtrlPanel_Stand4::GetCaption()
{
	CString result;
	GetProperty(DISPID_CAPTION, VT_BSTR, (void*)&result);
	return result;
}

void CSemCoreCtrlPanel_Stand4::SetCaption(LPCTSTR propVal)
{
	SetProperty(DISPID_CAPTION, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CSemCoreCtrlPanel_Stand4 operations

void CSemCoreCtrlPanel_Stand4::Bind(const VARIANT& ClassID, const VARIANT& SerialNumber)
{
	CSemCoreCtrlPanelCommonMap::Bind( ClassID, SerialNumber );

	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &ClassID, &SerialNumber);
}

void CSemCoreCtrlPanel_Stand4::Enable(const VARIANT& Enabled, const VARIANT& Flag)
{
	CSemCoreCtrlPanelCommonMap::Enable( Enabled, Flag );

	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &Enabled, &Flag);
}

void CSemCoreCtrlPanel_Stand4::SetRange(const VARIANT& Xmin, const VARIANT& Xmax, const VARIANT& Ymin, const VARIANT& Ymax)
{
	CSemCoreCtrlPanelCommonMap::SetRange( Xmin, Xmax, Ymin, Ymax );

	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &Xmin, &Xmax, &Ymin, &Ymax);
}

void CSemCoreCtrlPanel_Stand4::SetPos(const VARIANT& Xpos, const VARIANT& Ypos, const VARIANT& Flag)
{
	CSemCoreCtrlPanelCommonMap::SetPos( Xpos, Ypos, Flag );

	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &Xpos, &Ypos, &Flag);
}

void CSemCoreCtrlPanel_Stand4::SyncPos(const VARIANT& Xpos, const VARIANT& Ypos, const VARIANT& Flag)
{
	CSemCoreCtrlPanelCommonMap::SyncPos( Xpos, Ypos, Flag );

	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &Xpos, &Ypos, &Flag);
}

void CSemCoreCtrlPanel_Stand4::SyncText(LPCTSTR strX, LPCTSTR strY, const VARIANT& Flag)
{
	CSemCoreCtrlPanelCommonMap::SyncText( strX, strY, Flag);

	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_VARIANT;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strX, strY, &Flag);
}

void CSemCoreCtrlPanel_Stand4::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
