#if !defined(AFX_SEMCORECTRLPANEL_STAND5_H__DB05359B_46D8_4363_9F2D_0102F8AC772F__INCLUDED_)
#define AFX_SEMCORECTRLPANEL_STAND5_H__DB05359B_46D8_4363_9F2D_0102F8AC772F__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.
#include "SemCoreCtrlPanelCommonMap.h"

/////////////////////////////////////////////////////////////////////////////
// CSemCoreCtrlPanel_Stand5 wrapper class

class CSemCoreCtrlPanel_Stand5 : public CSemCoreCtrlPanelCommonMap
{
protected:
	DECLARE_DYNCREATE(CSemCoreCtrlPanel_Stand5)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x96e0ed82, 0xf866, 0x44f0, { 0x9b, 0xeb, 0xe0, 0x70, 0x19, 0x45, 0xfc, 0x1c } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetCaption();
	void SetCaption(LPCTSTR);
	short GetControlStyle();
	void SetControlStyle(short);
	short GetScaleDecimals();
	void SetScaleDecimals(short);
	short GetValueDecimals();
	void SetValueDecimals(short);

// Operations
public:
	void Bind(const VARIANT& ClassID, const VARIANT& SerialNumber);
	void Enable(const VARIANT& Enabled, const VARIANT& Flag);
	void SetRange(const VARIANT& Xmin, const VARIANT& Xmax, const VARIANT& Ymin, const VARIANT& Ymax);
	void SetPos(const VARIANT& Xpos, const VARIANT& Ypos, const VARIANT& Flag);
	void SyncPos(const VARIANT& Xpos, const VARIANT& Ypos, const VARIANT& Flag);
	void SyncText(LPCTSTR strX, LPCTSTR strY, const VARIANT& Flag);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SEMCORECTRLPANEL_STAND5_H__DB05359B_46D8_4363_9F2D_0102F8AC772F__INCLUDED_)
