// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "semcorectrlpanel_stand6.h"

// Dispatch interfaces referenced by this interface
#include "font.h"

/////////////////////////////////////////////////////////////////////////////
// CSemCoreCtrlPanel_Stand6

IMPLEMENT_DYNCREATE(CSemCoreCtrlPanel_Stand6, CSemCoreCtrlPanelCommonMap)

/////////////////////////////////////////////////////////////////////////////
// CSemCoreCtrlPanel_Stand6 properties

BOOL CSemCoreCtrlPanel_Stand6::GetCaptionVisible()
{
	BOOL result;
	GetProperty(0x1, VT_BOOL, (void*)&result);
	return result;
}

void CSemCoreCtrlPanel_Stand6::SetCaptionVisible(BOOL propVal)
{
	SetProperty(0x1, VT_BOOL, propVal);
}

OLE_COLOR CSemCoreCtrlPanel_Stand6::GetBackColor()
{
	OLE_COLOR result;
	GetProperty(DISPID_BACKCOLOR, VT_I4, (void*)&result);
	return result;
}

void CSemCoreCtrlPanel_Stand6::SetBackColor(OLE_COLOR propVal)
{
	SetProperty(DISPID_BACKCOLOR, VT_I4, propVal);
}

OLE_COLOR CSemCoreCtrlPanel_Stand6::GetForeColor()
{
	OLE_COLOR result;
	GetProperty(DISPID_FORECOLOR, VT_I4, (void*)&result);
	return result;
}

void CSemCoreCtrlPanel_Stand6::SetForeColor(OLE_COLOR propVal)
{
	SetProperty(DISPID_FORECOLOR, VT_I4, propVal);
}

COleFont CSemCoreCtrlPanel_Stand6::GetFont()
{
	LPDISPATCH pDispatch;
	GetProperty(DISPID_FONT, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CSemCoreCtrlPanel_Stand6::SetFont(LPDISPATCH propVal)
{
	SetProperty(DISPID_FONT, VT_DISPATCH, propVal);
}

CString CSemCoreCtrlPanel_Stand6::GetCaption()
{
	CString result;
	GetProperty(DISPID_CAPTION, VT_BSTR, (void*)&result);
	return result;
}

void CSemCoreCtrlPanel_Stand6::SetCaption(LPCTSTR propVal)
{
	SetProperty(DISPID_CAPTION, VT_BSTR, propVal);
}

BOOL CSemCoreCtrlPanel_Stand6::GetDebugInfoVisible()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CSemCoreCtrlPanel_Stand6::SetDebugInfoVisible(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

BOOL CSemCoreCtrlPanel_Stand6::GetGradeVisible()
{
	BOOL result;
	GetProperty(0x5, VT_BOOL, (void*)&result);
	return result;
}

void CSemCoreCtrlPanel_Stand6::SetGradeVisible(BOOL propVal)
{
	SetProperty(0x5, VT_BOOL, propVal);
}

CString CSemCoreCtrlPanel_Stand6::GetXMinString()
{
	CString result;
	GetProperty(0x3, VT_BSTR, (void*)&result);
	return result;
}

void CSemCoreCtrlPanel_Stand6::SetXMinString(LPCTSTR propVal)
{
	SetProperty(0x3, VT_BSTR, propVal);
}

CString CSemCoreCtrlPanel_Stand6::GetXMaxString()
{
	CString result;
	GetProperty(0x4, VT_BSTR, (void*)&result);
	return result;
}

void CSemCoreCtrlPanel_Stand6::SetXMaxString(LPCTSTR propVal)
{
	SetProperty(0x4, VT_BSTR, propVal);
}

unsigned long CSemCoreCtrlPanel_Stand6::GetGradeColor()
{
	unsigned long result;
	GetProperty(0x7, VT_I4, (void*)&result);
	return result;
}

void CSemCoreCtrlPanel_Stand6::SetGradeColor(unsigned long propVal)
{
	SetProperty(0x7, VT_I4, propVal);
}

COleFont CSemCoreCtrlPanel_Stand6::GetGradeFont()
{
	LPDISPATCH pDispatch;
	GetProperty(0x8, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CSemCoreCtrlPanel_Stand6::SetGradeFont(LPDISPATCH propVal)
{
	SetProperty(0x8, VT_DISPATCH, propVal);
}

short CSemCoreCtrlPanel_Stand6::GetGradeState()
{
	short result;
	GetProperty(0x9, VT_I2, (void*)&result);
	return result;
}

void CSemCoreCtrlPanel_Stand6::SetGradeState(short propVal)
{
	SetProperty(0x9, VT_I2, propVal);
}

BOOL CSemCoreCtrlPanel_Stand6::GetAutoVisible()
{
	BOOL result;
	GetProperty(0x6, VT_BOOL, (void*)&result);
	return result;
}

void CSemCoreCtrlPanel_Stand6::SetAutoVisible(BOOL propVal)
{
	SetProperty(0x6, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CSemCoreCtrlPanel_Stand6 operations

void CSemCoreCtrlPanel_Stand6::Bind(const VARIANT& ClassID, const VARIANT& SerialNumber)
{
	CSemCoreCtrlPanelCommonMap::Bind( ClassID, SerialNumber );

	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &ClassID, &SerialNumber);
}

void CSemCoreCtrlPanel_Stand6::Enable(const VARIANT& Enabled, const VARIANT& Flag)
{
	CSemCoreCtrlPanelCommonMap::Enable( Enabled, Flag );

	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &Enabled, &Flag);
}

void CSemCoreCtrlPanel_Stand6::SetRange(const VARIANT& Xmin, const VARIANT& Xmax, const VARIANT& Ymin, const VARIANT& Ymax)
{
	CSemCoreCtrlPanelCommonMap::SetRange( Xmin, Xmax, Ymin, Ymax );

	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &Xmin, &Xmax, &Ymin, &Ymax);
}

void CSemCoreCtrlPanel_Stand6::SetPos(const VARIANT& Xpos, const VARIANT& Ypos, const VARIANT& Flag)
{
	CSemCoreCtrlPanelCommonMap::SetPos( Xpos, Ypos, Flag );

	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &Xpos, &Ypos, &Flag);
}

void CSemCoreCtrlPanel_Stand6::SyncPos(const VARIANT& Xpos, const VARIANT& Ypos, const VARIANT& Flag)
{
	CSemCoreCtrlPanelCommonMap::SyncPos( Xpos, Ypos, Flag );

	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0xe, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &Xpos, &Ypos, &Flag);
}

void CSemCoreCtrlPanel_Stand6::SyncText(LPCTSTR strX, LPCTSTR strY, const VARIANT& Flag)
{
	CSemCoreCtrlPanelCommonMap::SyncText(strX, strY, Flag);

	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_VARIANT;
	InvokeHelper(0xf, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strX, strY, &Flag);
}

void CSemCoreCtrlPanel_Stand6::SyncResString(const VARIANT& ResourceID, LPCTSTR strRes)
{
	static BYTE parms[] =
		VTS_VARIANT VTS_BSTR;
	InvokeHelper(0x10, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &ResourceID, strRes);
}

void CSemCoreCtrlPanel_Stand6::SyncString(const VARIANT& ResourceID, const VARIANT& ResourceString)
{
	static BYTE parms[] =
		VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x11, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &ResourceID, &ResourceString);
}

void CSemCoreCtrlPanel_Stand6::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
